eventFlagIndex = 0;
eventFlagRequiredState = true;

var _player = global.singletonID[? PLAYER];
ds_list_add(sceneData,
	[cutscene_move_camera_position, 280, 250, 0.25, false],
	[cutscene_move_entity, 250, 250, true, _player],
	[cutscene_wait, 0.5],
	[cutscene_init_textbox],
	[create_textbox_actor_portrait, "This is a test of the cutscene system!", Actor.Claire, 6],
	[create_textbox_actor_portrait, "Hopefully this all works as it should work!", Actor.Claire, 1],
	[cutscene_end_textbox],
	[cutscene_wait, 1.5],
	[cutscene_move_camera_object, _player, 0.25, true],
	[cutscene_move_entity, 120, 100, true, _player],
	[cutscene_wait, 0.5],
	[cutscene_init_textbox],
	[create_textbox, "There's a lot of blood on that table..."],
	[cutscene_end_textbox],
	[cutscene_wait, 0.5],
	[cutscene_begin_screen_fade, c_black, 0.05, true],
	[cutscene_set_camera_position, 600, 120],
	[cutscene_create_item, 600, 170, PUMP_SHOTGUN, 3, 16],
	[cutscene_set_entity_position, 360, 120, _player],
	[cutscene_end_screen_fade, 0.05, true],
	[cutscene_move_entity, 600, 120, true, _player],
	[cutscene_wait, 0.5],
	[cutscene_init_textbox],
	[create_textbox_actor_portrait, "I'm surprised this fading stuff actually worked!", Actor.Claire, 0],
	[cutscene_end_textbox],
	[cutscene_wait, 0.5],
	[cutscene_set_entity_direction, 270, _player],
	[cutscene_wait, 0.5],
	[cutscene_init_textbox],
	[create_textbox_actor_portrait, "Hey... what's that on the ground...?", Actor.Claire, 0],
	[cutscene_end_textbox],
	[cutscene_wait, 0.5],
	[cutscene_move_camera_position, 600, 170, 0.25, false],
	[cutscene_activate_entity, obj_test_cutscene_entity],
	[cutscene_move_entity, 600, 180, false, obj_test_cutscene_entity],
	[cutscene_init_textbox],
	[create_textbox_actor, "WAIT JUST A MINUTE!", Actor.Unknown],
	[cutscene_end_textbox],
	[cutscene_wait, 0.5],
	[cutscene_init_textbox],
	[create_textbox_actor_portrait, "What the...", Actor.Claire, 0],
	[create_textbox_actor_portrait, "WHY DO YOU LOOK JUST LIKE ME!?!", Actor.Claire, 5],
	[cutscene_end_textbox],
	[cutscene_init_textbox],
	[create_textbox_actor, "Oh? That's a simple answer...", Actor.Unknown],
	[cutscene_end_textbox],
	[cutscene_wait, 0.5],
	[cutscene_move_camera_position, 600, 140, 0.25, false],
	[cutscene_move_entity, 600, 150, false, obj_test_cutscene_entity],
	[cutscene_init_textbox],
	[create_textbox_actor, "I am you... And you are me...", Actor.Unknown],
	[cutscene_end_textbox],
	[cutscene_wait, 1.0],
	[cutscene_move_entity, 600, 300, false, obj_test_cutscene_entity],
	[cutscene_init_textbox],
	[create_textbox_actor_portrait, "...", Actor.Claire, 1],
	[create_textbox_actor_portrait, "How...?", Actor.Claire, 1],
	[create_textbox_actor_portrait, "GET BACK HERE!!!", Actor.Claire, 5],
	[cutscene_end_textbox],
	[cutscene_wait, 0.5],
	[cutscene_deactivate_entity, obj_test_cutscene_entity],
	[cutscene_move_camera_object, _player, 0.25, false],
	[cutscene_move_entity, 600, 260, false, _player],
	[cutscene_wait, 0.5],
	[cutscene_init_textbox],
	[create_textbox_actor_portrait, "Where did they...", Actor.Claire, 1],
	[create_textbox_actor_portrait, "What the hell is going on?!", Actor.Claire, 5],
	[cutscene_end_textbox],
	[cutscene_set_flag, eventFlagIndex, eventFlagRequiredState],
	[cutscene_wait_for_entity_movement, _player],
);